// clients/vue/src/ParticipantsBar.vue
<template>
  <div class="sv-participants-bar" :style="barStyle">
    <div v-if="props.model.roomId" :style="{ color: '#555' }">
      Room:
      <strong data-testid="room-id">{{ props.model.roomId }}</strong>
    </div>
    <div :style="{ flex: 1 }" />
    <div
      data-testid="participants"
      role="list"
      aria-label="Participants"
      :style="{ display: 'flex', alignItems: 'center', paddingRight: '3px' }"
    >
      <div
        v-for="(chip, index) in props.model.chips"
        :key="chip.id"
        role="listitem"
        :title="chip.title"
        :style="{ display: 'inline-flex' }"
      >
        <span :style="chipCircleStyle(chip.color, index + 1)">{{
          chip.initials
        }}</span>
        <span :style="visuallyHidden">{{ chip.title }}</span>
      </div>
      <div
        v-if="props.model.overflowCount > 0"
        role="listitem"
        :title="props.model.overflowTitle"
        :style="{ display: 'inline-flex' }"
      >
        <span
          :style="chipCircleStyle('#909090', props.model.chips.length + 1)"
          >+{{ props.model.overflowCount }}</span
        >
        <span :style="visuallyHidden">{{ props.model.overflowTitle }}</span>
      </div>
    </div>
    <button
      v-if="props.model.showInvite"
      type="button"
      data-testid="copy-link"
      aria-label="Copy invite link"
      :style="inviteStyle"
      @click="props.model.copyInviteLink()"
    >
      {{ props.model.inviteCaption }}
    </button>
  </div>
</template>

<script lang="ts" setup>
import { useBase } from "survey-vue3-ui";
import type { CSSProperties } from "vue";
import type { ParticipantsBarModel } from "../../../shared/participantsBar";

const props = defineProps<{
  model: ParticipantsBarModel;
}>();

useBase(() => props.model);

// Inline styles (no SCSS): the bar ships with the collab tooling and must not
// depend on the survey theme pipeline. Mirrors shared/participantsBarView.
const barBg = "#f5f5f5";
const barStyle: CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: "12px",
  padding: "8px 12px",
  background: barBg,
  borderBottom: "1px solid #d4d4d4",
  // Open Sans matches the survey theme below the bar; as app chrome the bar
  // no longer inherits the theme font from the survey.
  fontFamily: "Open Sans, sans-serif",
  fontSize: "14px",
};
const visuallyHidden: CSSProperties = {
  position: "absolute",
  width: "1px",
  height: "1px",
  overflow: "hidden",
  clip: "rect(0 0 0 0)",
  whiteSpace: "nowrap",
};
const inviteStyle: CSSProperties = {
  border: "none",
  borderRadius: "8px",
  padding: "8px 12px",
  background: "#19b394",
  color: "#fff",
  fontWeight: 600,
  cursor: "pointer",
};

function chipCircleStyle(background: string, zIndex: number): CSSProperties {
  return {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 600,
    background,
    boxShadow: "0 0 0 2px " + barBg,
    marginRight: "-3px",
    position: "relative",
    zIndex,
  };
}
</script>

// clients/angular/src/app/participants-bar/participants-bar.component.ts
import { Component, Input } from "@angular/core";
import { IBarChip, ParticipantsBarModel } from "../../../../../shared/participantsBar";

/**
 * The collab participants bar; app chrome rendered by AppComponent above the
 * survey. A plain zone-driven component on purpose: every model mutation
 * originates from a socket event or a click (both zone-patched), so default
 * change detection re-reads the model getters — no survey-core subscription
 * needed. Do NOT extend BaseAngular here: it is built for survey-internal
 * views that detach from the change-detection tree and re-render manually,
 * and stays permanently attached (busy-looping) when declared as app chrome.
 */
@Component({
  selector: "app-participants-bar",
  templateUrl: "./participants-bar.component.html"
})
export class ParticipantsBarComponent {
  @Input() model!: ParticipantsBarModel;
  // Inline styles (no SCSS): the bar ships with the collab tooling and must
  // not depend on the survey theme pipeline. Mirrors shared/participantsBarView.
  public barBg = "#f5f5f5";
  public chipRing(): string {
    return "0 0 0 2px " + this.barBg;
  }
  /**
   * REQUIRED: `model.chips` builds a fresh array of fresh objects on every
   * read, and this component is checked by zone-driven change detection.
   * Without trackBy, ngFor would recreate the chip DOM on every pass; the
   * resize that causes re-triggers the survey's (zone-patched) observers,
   * which schedules another pass — a busy loop that freezes the page as soon
   * as the roster is non-empty.
   */
  public trackChip(index: number, chip: IBarChip): string {
    return chip.id;
  }
}

<div
  class="sv-participants-bar"
  [ngStyle]="{
    display: 'flex',
    'align-items': 'center',
    gap: '12px',
    padding: '8px 12px',
    background: barBg,
    'border-bottom': '1px solid #d4d4d4',
    'font-family': 'Open Sans, sans-serif',
    'font-size': '14px'
  }"
>
  <div *ngIf="model.roomId" [ngStyle]="{ color: '#555' }">
    Room: <strong data-testid="room-id">{{ model.roomId }}</strong>
  </div>
  <div [ngStyle]="{ flex: 1 }"></div>
  <div
    data-testid="participants"
    role="list"
    aria-label="Participants"
    [ngStyle]="{ display: 'flex', 'align-items': 'center', 'padding-right': '3px' }"
  >
    <div
      *ngFor="let chip of model.chips; let i = index; trackBy: trackChip"
      role="listitem"
      [title]="chip.title"
      [ngStyle]="{ display: 'inline-flex' }"
    >
      <span
        [ngStyle]="{
          width: '28px',
          height: '28px',
          'border-radius': '50%',
          'box-sizing': 'border-box',
          display: 'inline-flex',
          'align-items': 'center',
          'justify-content': 'center',
          color: '#fff',
          'font-size': '12px',
          'font-weight': 600,
          background: chip.color,
          'box-shadow': chipRing(),
          'margin-right': '-3px',
          position: 'relative',
          'z-index': i + 1
        }"
        >{{ chip.initials }}</span
      >
      <span
        [ngStyle]="{
          position: 'absolute',
          width: '1px',
          height: '1px',
          overflow: 'hidden',
          clip: 'rect(0 0 0 0)',
          'white-space': 'nowrap'
        }"
        >{{ chip.title }}</span
      >
    </div>
    <div
      *ngIf="model.overflowCount > 0"
      role="listitem"
      [title]="model.overflowTitle"
      [ngStyle]="{ display: 'inline-flex' }"
    >
      <span
        [ngStyle]="{
          width: '28px',
          height: '28px',
          'border-radius': '50%',
          'box-sizing': 'border-box',
          display: 'inline-flex',
          'align-items': 'center',
          'justify-content': 'center',
          color: '#fff',
          'font-size': '12px',
          'font-weight': 600,
          background: '#909090',
          'box-shadow': chipRing(),
          'margin-right': '-3px',
          position: 'relative',
          'z-index': model.chips.length + 1
        }"
        >+{{ model.overflowCount }}</span
      >
    </div>
  </div>
  <button
    *ngIf="model.showInvite"
    type="button"
    data-testid="copy-link"
    aria-label="Copy invite link"
    (click)="model.copyInviteLink()"
    [ngStyle]="{
      border: 'none',
      'border-radius': '8px',
      padding: '8px 12px',
      background: '#19b394',
      color: '#fff',
      'font-weight': 600,
      cursor: 'pointer'
    }"
  >
    {{ model.inviteCaption }}
  </button>
</div>
